services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://admin:adminpass@db:5432/notesdb
    ports:
      - "7071:7071"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:

